# Generated by Django 4.1.1 on 2022-10-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
