# Generated by Django 4.1.1 on 2022-11-06 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_classroom_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_article_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='classroom.classroom'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
