# Generated by Django 4.1.1 on 2022-11-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articlecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
