# Generated by Django 4.1.1 on 2022-11-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='submission_time',
            new_name='comment_time',
        ),
    ]
