# Generated by Django 4.1.1 on 2022-11-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_submission_time_articlecomment_comment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='file',
            new_name='comment_image',
        ),
    ]
