# Generated by Django 4.1.1 on 2022-11-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_file_articlecomment_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to='comment'),
        ),
    ]
