# Generated by Django 4.1.1 on 2022-11-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignmentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='turn_in_status',
            field=models.CharField(default='timely', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
